language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- npm install -g bower grunt-cli
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
before_install:
- openssl aes-256-cbc -K $encrypted_47448a2c7bc2_key -iv $encrypted_47448a2c7bc2_iv
  -in id_rsa.enc -out id_rsa -d
after_success:
- chmod 600 id_rsa
- cp id_rsa ~/.ssh/id_rsa
- rm -rf _deploy
- mkdir _deploy
- cd _deploy
- git remote add deploy pi@hermesiot.ddns.net:/home/pi/repo/datafest.git
- git push deploy master